# group_vars/fgsp.yml

# # Aggregates/zones **identical for all FGSP members**
# vdoms:
#   - name: root
#     mgmt: true
#   - name: traffic

# networks:
#   dc_lan: "10.10.10.0/24"
#   prem_lan: "10.10.20.0/24"
#   sync1: "10.10.30.0/24"
#   sync2: "10.10.40.0/24"
#   loopback: "10.10.255.0/24"

aggregate:
  - name: "agg"
    members: ["x3", "x4"]
    lacp: "active"
    vdom: root

interfaces:
  - name: vl_dc
    vdom: traffic
    type: vlan
    interface: agg
    vlanid: 100
    network: dc_lan
    allowaccess: [ping]
  - name: lo1
    vdom: traffic
    type: loopback
    network: loopback
    allowaccess: [ping]

  - name: vl_prem
    vdom: traffic
    type: vlan
    network: prem_lan
    interface: agg
    vlanid: 200
    allowaccess: [ping]
  - name: ha
    vdom: root
    ha_sync: true
    alias: sync1
    network: sync1
    allowaccess: [ping]
  - name: port1
    vdom: root
    ha_sync: true
    alias: sync2
    network: sync2
    allowaccess: [ping]

zones:
  - { name: "to_prem", interfaces: ["vl_prem"], vdom: "traffic" }
  - { name: "to_dc", interfaces: ["vl_dc"], vdom: "traffic" }

# FGSP specific (session sync / standalone cluster)
fgsp:
  session_pickup: "enable"
  psksecret: "fortinet123"
  standalone_group_id: 0
  session_pickup_connectionless: "enable"
  session_pickup_expectation: "enable"
  # peers are resolved from group hosts dynamically; you can pin HB interface if desired
  # hb_interface: "sync1" # example; or a dedicated VLAN subint if you prefer

# BGP (peers will be the bookends + optional intra-FGSP adjacencies as needed)
bgp:
  vdom: "traffic"
  local_as: 65010
  ebgp_multipath: enable
  soft_reconfiguration: enable
  bfd: enable
  # neighbors:
  #   - name: fgt_rt1

  #   - name: fgt_rt2

  # remote_as:
  #   dc_lan: 65001
  #   prem_lan: 65002
