vxlan:
  - name: "vni.100"
    interface: loop1
    vlanid: 100
    vni: 100
    evpn: enable
    arp_nd_suppression: enable
  - name: "vni.200"
    interface: loop1
    vlanid: 200
    vni: 200
    evpn: enable
    arp_nd_suppression: enable

bgp_leaf:
  maximum_paths_ibgp: 2

switch_system_interface:
  - name: mgmt
    type: physical
    secondary_ip: disable
    allowaccess: ["ping", "http", "https", "ssh", "snmp"]
  - name: RVI11
    type: physical
    description: "to spine"
    l2_interface: "port1"
  - name: SVI100
    vlanid: 100
    interface: "internal"
  - name: SVI200
    vlanid: 200
    interface: "internal"

switch_interface:
  - name: port5
    native_vlan: 100
  - name: port6
    native_vlan: 100
  - name: port7
    native_vlan: 100
  - name: port8
    native_vlan: 100
  - name: port9
    native_vlan: 200
  - name: port10
    native_vlan: 200
  - name: port11
    native_vlan: 200
  - name: port12
    native_vlan: 200
  - name: fgt_fgsp
    native_vlan: 1
    allowed_vlans: "100 200"
  - name: fgt_fgsp2
    native_vlan: 1
    allowed_vlans: "100 200"
  - name: fgt_fgsp3
    native_vlan: 1
    allowed_vlans: "100 200"
  - name: fgt_fgsp4
    native_vlan: 1
    allowed_vlans: "100 200"
trunk:
  - name: fgt_fgsp
    members:
      - member_name: port13
      - member_name: port14
    description: "to_fgsp_fgt"
  - name: fgt_fgsp2
    members:
      - member_name: port15
      - member_name: port16
    description: "to_fgsp_fgt"
  - name: fgt_fgsp3
    members:
      - member_name: port17
      - member_name: port18
    description: "to_fgsp_fgt"
  - name: fgt_fgsp4
    members:
      - member_name: port19
      - member_name: port20
    description: "to_fgsp_fgt"
vlan:
  - name: prem_lan
    id: 200
  - name: dc_lan
    id: 100
