zones:
  - { name: "to_prem", interfaces: ["x4"], vdom: "traffic" }
  - { name: "to_dc", interfaces: ["x3"], vdom: "traffic" }

router_net: prem_lan

interfaces:
  - name: x3
    vdom: traffic
    # default_gw: true
    network: prem_lan
    allowaccess: [ping]
  - name: x4
    vdom: traffic
    default_gw: true
    network: prem_fts
    allowaccess: [ping]
  - name: lo1
    vdom: traffic
    type: loopback
    network: loopback
    allowaccess: [ping]

static_routes:
  - id: 10
    vdom: traffic
    int: "x4"
    gateway: 10.200.0.1
    dst: 10.200.0.0/16
  - id: 101
    vdom: traffic
    dst: 10.0.0.0/8
    blackhole: enable
  - id: 19
    vdom: traffic
    dst: 172.19.0.0/16
    blackhole: enable
  - id: 20
    vdom: traffic
    dst: 172.20.0.0/16
    blackhole: enable
  - id: 21
    vdom: traffic
    dst: 172.21.0.0/16
    blackhole: enable
