# inventory.yml
all:
  children:
    local:
      hosts:
        localhost: { ansible_connection: localhost }
    fgsp:
      hosts:
        fgsp_fgt1: { ansible_host: 192.168.5.141, fw_index: 1 }
        fgsp_fgt2: { ansible_host: 192.168.5.142, fw_index: 2 }
        fgsp_fgt3: { ansible_host: 192.168.5.143, fw_index: 3 }
        fgsp_fgt4: { ansible_host: 192.168.5.144, fw_index: 4 }
    fgt_rt:
      hosts:
        fgt_rt1: { ansible_host: 192.168.5.145, fw_index: 101 }
        fgt_rt2: { ansible_host: 192.168.5.146, fw_index: 102 }
    fsw_spine:
      hosts:
        fsw_spine1: { ansible_host: 192.168.5.147 }
    fsw_leaf:
      hosts:
        fsw_leaf1: { ansible_host: 192.168.5.148 }
        fsw_leaf2: { ansible_host: 192.168.5.149 }
        fsw_leaf3: { ansible_host: 192.168.5.150 }
    allfsw:
      children:
        fsw_spine:
        fsw_leaf:
      vars:
        ansible_network_os: fortinet.fortiswitch.fortiswitch
        ansible_connection: httpapi
        ansible_httpapi_use_ssl: true
        ansible_httpapi_validate_certs: false
        ansible_httpapi_port: 443
    allfgt:
      children:
        fgsp:
        fgt_rt:
      vars:
        ansible_connection: httpapi
        ansible_network_os: fortinet.fortios.fortios
        ansible_httpapi_use_ssl: true
        ansible_httpapi_validate_certs: false
        ansible_httpapi_port: 443
