# - name: Select Traffic Interfaces
#   ansible.builtin.set_fact:
#     traffic_int: "{{ interfaces | selectattr('vdom','defined') | selectattr('vdom','ne','root')| map(attribute='name') | list }}"

# - name: Debug BGP peers
#   ansible.builtin.debug:
#     var: interfaces | rejectattr('vdom','equalto','root') | list

# - name: Select Peers for Traffic (last 2 IPs of subnet)
#   ansible.builtin.set_fact:
#     bgp_peer: "{{ bgp_peer | default([]) + [{
#       'vdom': item.vdom,
#       'interface': item.name,
#       'ip': (networks[item.network] | ansible.utils.ipmath(fw_index) ),
#       'bgp_peer': (networks[item.network] | ansible.utils.ipmath(-2) ),
#       'bgp_as': (bgp.remote_as[item.network] | default(''))
#       }]
#       }}"
#   loop: "{{ interfaces }}"
#   when: item.vdom is defined and item.vdom != 'root'
# # - name: Select Peers for Traffic (last 2 IPs of subnet)
# #   ansible.builtin.set_fact:
# #     bgp_peer_format: |-
# #       {%- set p = {} -%}
# #       {%- for int in (interfaces|default([]))  -%}
# #           {% set peer = (networks[item.network] | ansible.utils.ipmath(-2) ) | default('')  %}
# #               {%- if peer not in p -%}
# #                 {% set _ = p.update({ peer:[] }) -%}
# #               {%- endif -%}
# #                  {%- set _ = p[peer].append( bgp.remote_as[item.network] ) -%}
# #       {%- endfor -%}
# #       {{ p  }}
# #   loop: "{{ interfaces }}"
# #   when: item.vdom is defined and item.vdom != 'root'

# - name: Debug BGP peers
#   ansible.builtin.debug:
#     var: bgp_peer

# - meta:
#     end_host

- name: Configure BGP (FGSP)
  fortinet.fortios.fortios_router_bgp:
    vdom: "{{ item.name }}"
    router_bgp:
      as: "{{ bgp.local_as }}"
      router_id: "{{ networks['loopback'] | ansible.utils.ipmath( fw_index ) }}"
      ebgp_multipath: "{{ bgp.ebgp_multipath | default('enable') }}"
      redistribute: "{{ bgp_redistribute }}"
      neighbor:
        - ip: "{{ networks['dc_lan'] | ansible.utils.ipmath(hostvars['fgt_rt1'].fw_index)  }}"
          soft_reconfiguration: "{{ bgp.soft_reconfiguration | default('enable') }}"
          remote_as: "{{ hostvars['fgt_rt1'].fw_index + 65000  }}"
          next_hop_self: "{{ bgp.next_hop_self | default('enable') }}"
          bfd: "{{ bgp.bfd | default('enable') }}"
        - ip: "{{ networks['prem_lan'] | ansible.utils.ipmath(hostvars['fgt_rt2'].fw_index)  }}"
          soft_reconfiguration: "{{ bgp.soft_reconfiguration | default('enable') }}"
          remote_as: "{{ hostvars['fgt_rt2'].fw_index + 65000  }}"
          next_hop_self: "{{ bgp.next_hop_self | default('enable') }}"
          bfd: "{{ bgp.bfd | default('enable') }}"
  loop: "{{ vdoms }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - item.name is defined
    - item.name != 'root'
    - "'fgsp' in group_names"

- name: Build BGP for Routers
  when: "'fgt_rt' in group_names"
  block:
    - name: Calculate BGP Peers
      ansible.builtin.set_fact:
        fgsp_bgp_peers: >-
          {{
                groups['fgsp']
                | map('extract',hostvars)
                | map(attribute='fw_index')
                | list
          }}
        fgsp_any: "{{ groups['fgsp'] | default([]) | first }}"
    - name: Loop BGP Config
      ansible.builtin.set_fact:
        _neighbor: >-
          {{ (_neighbor | default([]) + [ {
            'ip': ( networks[router_net] | ansible.utils.ipmath(item) ),
            'remote_as': (hostvars[fgsp_any].bgp.local_as),
            'soft_reconfiguration':  (bgp.soft_reconfiguration | default('enable')),
            'next_hop_self': (bgp.next_hop_self | default('enable')),
            'bfd': (bgp.bfd | default('enable'))
            }])
          }}
      loop: "{{ fgsp_bgp_peers }}"
      loop_control:
        label: "{{ item }}"

    - name: Apply Router BGP Config
      fortinet.fortios.fortios_router_bgp:
        vdom: "{{ traffic_vdom }}"
        router_bgp:
          as: "{{ 65000 + fw_index }}"
          router_id: "{{ networks['loopback'] | ansible.utils.ipmath( fw_index ) }}"
          ebgp_multipath: "{{ bgp.ebgp_multipath | default('enable') }}"
          redistribute: "{{ bgp_redistribute }}"
          neighbor:
            "{{_neighbor | default(omit) }}"
            # - ip: "{{ networks[router_net] | ansible.utils.ipmath(hostvars['fgt_rt1'].fw_index)  }}"
            #   soft_reconfiguration: "{{ bgp.soft_reconfiguration | default('enable') }}"
            #   remote_as: "{{ hostvars['fgt_rt1'].fw_index + 65000  }}"
            #   next_hop_self: "{{ bgp.next_hop_self | default('enable') }}"
            #   bfd: "{{ bgp.bfd | default('enable') }}"
            # - ip: "{{ networks['prem_lan'] | ansible.utils.ipmath(hostvars['fgt_rt2'].fw_index)  }}"
            #   soft_reconfiguration: "{{ bgp.soft_reconfiguration | default('enable') }}"
            #   remote_as: "{{ hostvars['fgt_rt2'].fw_index + 65000  }}"
            #   next_hop_self: "{{ bgp.next_hop_self | default('enable') }}"
            #   bfd: "{{ bgp.bfd | default('enable') }}"
      # loop: "{{ vdoms }}"
      # loop_control:
      #   label: "{{ item.name }}"
