- name: Dump FGSP Settings
  ansible.builtin.debug:
    msg: "Executing FGSP test"

- name: Build list of FGSP peer hostnames (exclude self)
  ansible.builtin.set_fact:
    fgsp_peers: >-
      {{
        (groups['fgsp'] | difference([inventory_hostname])) | sort
      }}
    fgsp_peer_count: "{{ groups['fgsp'] | length }}"

- name: Build list of FGSP sync interfaces
  ansible.builtin.set_fact:
    fgsp_sync_int: "{{ interfaces | selectattr('ha_sync','defined') | selectattr('ha_sync','equalto',true)| map(attribute='name') | list }}"

- name: Build Syncvd List
  ansible.builtin.set_fact:
    fgsp_syncvd_list: "{{ vdoms | rejectattr('name', 'equalto', 'root') | map(attribute='name') | map('community.general.dict_kv', 'name') | list }}"

#### Add +1 to loop index so we start at 1 instead of 0.
- name: Build cluster_peer
  ansible.builtin.set_fact:
    cluster_peer: "{{ (cluster_peer | default([])) + [ {
      'peerip':  (networks['sync1'] | ansible.utils.ipmath( hostvars[item].fgsp_index)),
      'peervd':  'root',
      'sync_id': loop_index+1,
      'syncvd':   fgsp_syncvd_list
      } ] }}"
  loop: "{{ fgsp_peers  }}"
  loop_control:
    label: "{{ item }}"
    index_var: loop_index

# - name: Debug Peers
#   ansible.builtin.debug:
#     var: cluster_peer
### Add peer count so we start in the next sequential order
- name: Append  cluster_peer
  ansible.builtin.set_fact:
    cluster_peer: "{{ (cluster_peer | default([])) + [ {
      'peerip':  (networks['sync2'] | ansible.utils.ipmath( hostvars[item].fgsp_index)),
      'peervd':  'root',
      'sync_id': loop_index+fgsp_peer_count,
      'syncvd':   fgsp_syncvd_list
      } ] }}"
  loop: "{{ fgsp_peers }}"
  loop_control:
    label: "{{ item }}"
    index_var: loop_index

# - name: Debug Peers
#   ansible.builtin.debug:
#     var: cluster_peer

- name: Configure FortiGate Session Life Support Protocol (FGSP) cluster attributes
  fortinet.fortios.fortios_system_standalone_cluster:
    vdom: "{{ vdom }}"
    system_standalone_cluster:
      cluster_peer: "{{cluster_peer}}"
      encryption: "enable"
      group_member_id: "{{ fgsp_index }}"
      layer2_connection: "available"
      # monitor_interface:
      #     -  name: "default_name_32 (source system.interface.name)"
      psksecret: "{{ fgsp.psksecret }}"
      session_sync_dev: "{{ fgsp_sync_int }}"
      standalone_group_id: "{{ fgsp.standalone_group_id }}"
      # utm_traffic_bounce: "enable"  <- 7.6.4 and later option

- name: Configure HA settings
  fortinet.fortios.fortios_system_ha:
    vdom: "{{ vdom }}"
    system_ha:
      session_pickup: "{{ fgsp.session_pickup | default('enable')  }}"
      session_pickup_connectionless: "{{ fgsp.session_pickup_connectionless | default('enable')  }}"
      session_pickup_expectation: "{{ fgsp.session_pickup_expectation | default('enable') }}"
