---
- name: FortiSwitch System Configuration
  hosts: allfsw
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Establish Paths
      ansible.builtin.import_tasks: "includes/pre_tasks.yml"

    - name: Administrative user configuration.
      fortinet.fortiswitch.fortiswitch_system_admin:
        state: "present"
        system_admin:
          name: "{{ ssh_admin_name }}"
          accprofile: "{{ ssh_admin_profile }}"
          password: "testing123"
          ssh_public_key1: "{{ ssh_pubkey }}"

    - name: Disable Auto-Network
      fortinet.fortiswitch.fortiswitch_switch_auto_network:
        switch_auto_network:
          status: "{{ switch_auto_network | default('disable') }}"

    - name: Disalbe auto-fortilink-discovery
      fortinet.fortiswitch.fortiswitch_switch_global:
        switch_global:
          auto_fortilink_discovery: "{{ auto_fortilink_discovery | default('disable')  }}"

    - name: Merge Loopback Interface
      ansible.builtin.set_fact:
        switch_system_interface: >-
          {{
            (switch_system_interface | default([]))
            + (loopback_switch_interface | default([]) )
            | list
          }}
      tags: [always]

    - name: Debug Switch Interface
      ansible.builtin.debug:
        var: switch_system_interface
      tags: [never, debug]

    - name: Configure interfaces
      fortinet.fortiswitch.fortiswitch_system_interface:
        state: "present"
        system_interface:
          name: "{{ item.name  }}"
          interface: "{{ item.interface | default(omit) }}"
          ip: "{{ item.ip | default(omit) }}"
          type: "{{ item.type | default(omit) }}"
          allowaccess: "{{ item.allowaccess | default(omit) }}"
          secondary_IP: "{{ item.secondary_ip | default(omit) }}"
          vlanid: "{{ item.vlanid | default(omit) }}"
          description: "{{ item.description | default(omit) }}"
          l2_interface: "{{ item.l2_interface | default(omit)  }}"
      loop: "{{ switch_system_interface }}"
      loop_control:
        label: "{{ item.name }}"
      tags: [always]

    - name: Debug
      debug:
        msg:
          router_id: "{{ switch_system_interface | selectattr('type','equalto','loopback')| map(attribute='ip') | first | split('/') | first }}"
          rvi: "{{ switch_system_interface | selectattr('l2_interface', 'defined') | map(attribute='name') | list }}"
      tags: [never, debug]

    - name: Calculate BGP Config
      ansible.builtin.set_fact:
        _bgp_ng_interface: >-
          {{ 
            switch_system_interface 
            | selectattr('l2_interface', 'defined') 
            | map(attribute='name') 
            | map('community.general.dict_kv', 'interface_name')
            | list 
          }}

    - name: debugg variable neighbor_group
      debug:
        var: _bgp_ng_interface
      tags: [never, debug]

    - name: debugg switch_system_interface
      debug:
        var: switch_system_interface
      tags: [never, debug]

    - name: debugg calculated interface
      debug:
        var: _bgp_ng_interface
      tags: [never, debug]

    - name: debugg calculated interface type
      debug:
        var: _bgp_ng_interface | type_debug
      tags: [never, debug]

    - name: debugg variable neighbor_group
      debug:
        var: bgp.neighbor_group
      tags: [never, debug]

    - name: debugg variable neighbor_group type
      debug:
        var: bgp.neighbor_group | type_debug
      tags: [never, debug]

    - name: Base neighbor_group with dynamic interfaces
      ansible.builtin.set_fact:
        _bgp_ng: >-
          {{ 
            bgp.neighbor_group 
            | map('combine', {'interface': _bgp_ng_interface}) 
            | list 
          }}

    - name: debug merged neighbor group interface
      debug:
        var: _bgp_ng
      tags: [never, debug]

    - name: Append Spine BGP config as needed
      ansible.builtin.set_fact:
        _bgp_ng: >-
          {{
            _bgp_ng 
            |  map('combine', bgp.spine_config) 
            | list  
          }}
      when: "'fsw_spine' in group_names"

    - name: debug router-id
      debug:
        msg:
          router-id: "{{ switch_system_interface | selectattr('type','equalto','loopback')| map(attribute='ip') | first | split('/') | first }}"
      tags: [never, debug]

    - name: Set router-id
      ansible.builtin.set_fact:
        router_id: "{{ loopback_switch_interface | map(attribute='ip') | first | split('/') | first }}"

    - name: BGP configuration
      fortinet.fortiswitch.fortiswitch_router_bgp:
        router_bgp:
          # router_id: "{{ switch_system_interface | selectattr('type','equalto','loopback')| map(attribute='ip') | first | split('/') | first }}"
          router_id: "{{ router_id | default(omit) }}"
          maximum_paths_ibgp: "{{ bgp_leaf.maximum_paths_ibgp | default(omit) }}"
          as: "{{ bgp.as | default(omit) }}"
          redistribute: "{{ bgp.redistribute | default(omit) }}"
          neighbor_group: "{{ _bgp_ng }}"

    - name: Generate FSW evpn VXLAN/BGP Leaf Config
      ansible.builtin.set_fact:
        _switch_cli_command: "{{ lookup('template', template_path) }}"
      vars:
        template_path: "{{ playbook_dir }}/template/fortiswitch_evpn.j2"


    - name: Generate FSW CLI file for reference
      ansible.builtin.template:
        src: "{{template_path}}"
        dest: "{{debug_dir}}/{{inventory_hostname}}_cli.txt"
        mode: "0644"
      vars:
        template_path: "{{ playbook_dir }}/template/fortiswitch_evpn.j2"
        debug_dir: "{{ playbook_dir }}../../debug"

    - name: Check for empty lines
      ansible.builtin.set_fact:
        _effective_lines: "{{ (_switch_cli_command | default('',true) | trim).splitlines() | map('trim') | select('match','^(config|edit|set|unset|next|end)\\b') | list }}"
      when: 
       - _switch_cli_command is defined 
      #  - _switch_cli_command | length > 0

    # - name: debug
    #   debug:
    #     var: _effective_lines | length
    
    # - meta: end_host


    - name: Push switch command via ssh if necessary
      ansible.builtin.command: >
        ssh -T -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null 
        -o LogLevel=ERROR -o GlobalKnownHostsFile=/dev/null
        -i {{ ssh_privkey_path }}
        {{ ssh_admin_name }}@{{ ansible_host}}
      args:
        stdin: "{{ _switch_cli_command ~ '\n' }}"
      delegate_to: local
      register: _ssh_check
      changed_when: false
      when: _effective_lines | length > 0
      # failed_when: _ssh_check.rc !=0 or _ssh_check.stderr | length > 0
      failed_when: _ssh_check.rc !=0 or ( _ssh_check.stderr |default('')) is regex('(?i)(error|unknown|invalid|syntax|command fail|failed)' ) or ( _ssh_check.stdout |default('')) is regex('(?i)(error|unknown|invalid|syntax|command fail|failed)' )

    - name: Check SSH command
      ansible.builtin.debug:
        var: _ssh_check
      when: _ssh_check is defined

    - name: PAUSE to review
      pause: 
        seconds: 15

    # - name: Configure VXLAN devices.
    #   fortinet.fortiswitch.fortiswitch_system_vxlan:
    #     state: "{{ item.state | default('present') }}"
    #     system_vxlan:
    #       interface: "{{ item.interface | default(omit) }}"
    #       name: "{{ item.name }}"
    #       vlanid: "{{ item.vlanid | default(omit) }}"
    #       vni: "{{ item.vni | default(omit) }}"
    #       evpn: "{{ item.evpn | default(omit) }}"
    #       arp-nd-suppression: "{{ item.arp_nd_suppression | default(omit) }}"
    #   loop: "{{ vxlan }}"
    #   when: "'fsw_leaf' in group_names"
    #   register: _vxlan_response
    #   ignore_errors: true

    # - debug:
    #     var: _vxlan_response

    # - meta: end_host  

    - name: Usable interfaces (trunks and ports).
      fortinet.fortiswitch.fortiswitch_switch_interface:
        state: "{{ item.state | default('present') }}"
        switch_interface:
          name: "{{ item.name  }}"
          native_vlan: "{{ item.native_vlan | default(omit) }}"
      loop: "{{ switch_interface }}"
      when:
        - switch_interface is defined
        - switch_interface | default([]) |  length > 0

    - name: Switch-global stp settings.
      fortinet.fortiswitch.fortiswitch_switch_stp_settings:
        switch_stp_settings:
          status: "disable"

    - name: Configure global settings.
      fortinet.fortiswitch.fortiswitch_switch_global:
        switch_global:
          vxlan_stp_virtual_root: "enable"

    - name: Configure Global settings
      fortinet.fortiswitch.fortiswitch_system_global:
        system_global:
          admintimeout: 20
