---
- name: FortiSwitch System Configuration
  hosts: fsw
  connection: httpapi
  gather_facts: false
  pre_tasks:
    - name: Establish Paths
      ansible.builtin.include_tasks: "includes/pre_tasks.yml"
  tasks:
###
### 1. Configure Management (likely done manually)
### 2. Disable Auto-ISL on Interfaces to prevent auto-link
    # config switch auto-network
    # set status disable
    # end
    # config switch global
    # set auto-fortilink-discovery disable
    # end

  - name: Disable Auto-Network
    fortinet.fortiswitch.fortiswitch_switch_auto_network:
      switch_auto_network:
          status: "{{ switch_auto_network | default('disable') }}"


  - name: Disalbe auto-fortilink-discovery
    fortinet.fortiswitch.fortiswitch_switch_global:
      switch_global:
        auto_fortilink_discovery: "{{ auto_fortilink_discovery | default('disable')  }}"


### 3. Config Interfaces (loopback and L3 interface)
    # config system interface
    #   edit "loopback"
    #   set type loopback
    #   set ip 10.255.0.201/32
    #   set allowaccess ping ssh
    # next
    # edit "RVI11"
    #   set type physical
    #   set l2-interface "port3"
    # next

  - name: Configure interfaces.
    fortinet.fortiswitch.fortiswitch_system_interface:
      state: "present"
      system_interface:
        name: "{{ item.name  }}"
        interface: "{{ item.interface | default(omit) }}"
        ip: "{{ item.ip | default(omit) }}"
        type: "{{ item.type | default(omit) }}"
        allowaccess: "{{ item.allowaccess | default(omit) }}"
        secondary_IP: "{{ item.secondary_ip | default(omit) }}"
        vlanid: "{{ item.vlanid | default(omit) }}"
        description: "{{ item.description | default(omit) }}"
        l2_interface: "{{ item.l2_interface | default(omit)  }}"
    loop: "{{ switch_system_interface }}"
    loop_control: 
      label: "{{ item.name }}"

### 4. Config BGP eVPN
    # config router bgp
    # set as 65001
    # set router-id 10.255.0.201
    #   config neighbor-group
    #     edit "ISL"
    #     set advertisement-interval 0
    #     set activate-evpn enable
    #     set bfd enable
    #     set capability-extended-nexthop enable
    #     set soft-reconfiguration enable
    #     set interface "RVI11" "RVI12" "RVI13" "RVI14"
    #     set remote-as "internal"
    #     set keep-alive-timer 3
    #     set holdtime-timer 9
    #     set route-reflector-client enable
    #     set route-reflector-client-evpn enable
    #     set password "fortinet"
    #   end
    #   config redistribute "connected"
    #     set status enable
    #   end
    # end
  # - name: Debug
  #   debug: 
  #     msg: 
  #       router_id: "{{ switch_system_interface | selectattr('type','equalto','loopback')| map(attribute='ip') | first | split('/') | first }}" 
  #       rvi: "{{ switch_system_interface | selectattr('l2_interface', 'defined') | map(attribute='name') | list }}"
  - name: Calculate BGP Config
    ansible.builtin.set_fact:
       _bgp_ng_interface: >-
        {{ 
          switch_system_interface 
          | selectattr('l2_interface', 'defined') 
          | map(attribute='name') 
          | list 
        }}

  - name: Base neighbor_group with dynamic interfaces
    ansible.builtin.set_fact:
      _bgp_ng: >-
        {{ 
          bgp.neighbor_group 
          | map('combine', {'interface': _bgp_ng_interface}) 
          | list 
        }}

  - name: Append Spine BGP config as needed
    ansible.builtin.set_fact:
      _bgp_ng: >- 
        {{
          _bgp_ng 
          |  map('combine', bgp.spine_config) 
          | list  
        }}
    when: bgp_role is defined and bgp_role == 'spine'

  - name: BGP configuration
    fortinet.fortiswitch.fortiswitch_router_bgp:
      router_bgp:
        router_id: "{{ switch_system_interface | selectattr('type','equalto','loopback')| map(attribute='ip') | first | split('/') | first }}" 
        maximum_paths_ibgp: "{{ bgp.maximum_paths_ibgp | default(omit) }}"
        as: "{{ bgp.as | default(omit) }}"
        redistribute: "{{ bgp.resdistribute | default(omit) }}"
        neighbor_group: "{{ _bgp_ng }}"

    #  ADD FOR LEAF:
    #   config evpn
    #   set advertise-vni enable
    #   config vni
    #     edit 100
    #       set rd <route distinguisher> <- optional
    #       set export-rt <route target to export> <- optional
    #       set import-rt <route target to import> <- optional
    #     next
    #     edit 200
    #     next
    #   end
  

### 5. Config Leaf switches. (Same interface + VLAN), similar BGP, add evpn
    # config system interface
    #   edit "SVI100"
    #     set vlanid 100
    #     set interface "internal"
    #   next
    #   edit "SVI200"
    #     set vlanid 200
    #     set interface "internal"
    #   next
    # end

    # config router bgp
    #   set as 65001
    #   set router-id 10.255.0.1
    #   set maximum-paths-ibgp 2
    #   config neighbor-group
    #     edit "ISL"
    #     set advertisement-interval 0
    #     set activate-evpn enable
    #     set bfd enable
    #     set capability-extended-nexthop enable
    #     set soft-reconfiguration enable
    #     set interface "RVI11" "RVI21"
    #     set remote-as "internal"
    #     set keep-alive-timer 3
    #     set holdtime-timer 9
    #     set password "fortinet“
    #   end
    #   config redistribute "connected"
    #     set status enable
    #   end
    #   config evpn
    #   set advertise-vni enable
    #   config vni
    #     edit 100
    #       set rd <route distinguisher> <- optional
    #       set export-rt <route target to export> <- optional
    #       set import-rt <route target to import> <- optional
    #     next
    #     edit 200
    #     next
    #   end

    
### 6. Config leaf VXLAN
    # config system vxlan
    #   edit "vni.100"
    #     set vni 100
    #     set vlanid 100
    #     set interface "loopback"
    #     set evpn enable
    #     set arp-nd-suppression enable
    #   next
    #   edit "vni.200"
    #     set vni 200
    #     set vlanid 200
    #     set interface "loopback"
    #     set evpn enable
    #     set arp-nd-suppression enable
    #   next
    # end
### 7. config switch access ports
    # config switch interface
    #   edit "port1"
    #     set native-vlan 100
    #   next
    #   edit "port2"
    #     set native-vlan 200
    #   next
    # end
### 8. Misc
  # config switch stp settings
  #   set status disable
  # end
  # config switch global
  #   set vxlan-stp-virtual-root enable
  # end


  - name: Debug Vars
    ansible.builtin.debug:
      var:  ansible_host 

  - name: Configure Global settings
    fortinet.fortiswitch.fortiswitch_system_global:
      system_global:
        admintimeout: 20

